import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>넥스트레블</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen justify-center items-center">
        <h1 className="text-7xl font-bold">넥스트레블</h1>
        <h2 className="text-3xl font-medium my-4">Our Apps</h2>
        <ul className="space-y-4">
          <li className="text-xl hover:font-medium cursor-pointer">
            <a>&rarr; 러브유</a>
          </li>
          <li className="text-xl hover:font-medium cursor-pointer">
            <a>&rarr; QR코드</a>
          </li>
          <Link href="https://nextlevel-monster.netlify.app">
            <li className="text-xl hover:font-medium cursor-pointer">
              <a>&rarr; 먼스터</a>
            </li>
          </Link>
        </ul>
        <footer className="fixed bottom-0 py-8">
          <div>mail : nextlevel99.help@gmail.com</div>
        </footer>
      </main>
    </div>
  );
}
